/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import Login.Screen;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

/**
 *
 * @author ADMIN
 */
public class MainScreen extends javax.swing.JFrame {

    private Screen screen;
    private NewMain newMain;
    private TestMain testMain;
    private BuyMain buyMain;
    

    public MainScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setupActions();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();
        jButtonTest = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonBuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        titleLabel.setText("HỆ THỐNG QUẢN LÝ SÁCH");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 240, 60));

        jButtonNew.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNew.setText("NEW");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 290, 50));

        jButtonTest.setBackground(new java.awt.Color(250, 250, 250));
        jButtonTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTest.setText("Test");
        getContentPane().add(jButtonTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, 50));

        jButtonExit.setBackground(new java.awt.Color(250, 250, 250));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.setActionCommand("");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 290, 50));

        jButtonBuy.setBackground(new java.awt.Color(250, 250, 250));
        jButtonBuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuy.setText("BUY");
        getContentPane().add(jButtonBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 290, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgMain.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    private void setupActions() {
        jButtonExit.addActionListener((ActionEvent actionEvent) -> {
            this.screen = screen == null ? new Screen() : screen;
            this.setVisible(false);
        });
         jButtonNew.addActionListener((ActionEvent actionEvent) -> {
            this.newMain = newMain == null ? new NewMain(): newMain; 
            this.setVisible(false);
        });
         jButtonTest.addActionListener((ActionEvent actionEvent) -> {
            this.testMain = testMain == null ? new TestMain() : testMain;
            this.setVisible(false);
         });
         jButtonBuy.addActionListener((ActionEvent actionEvent) -> {
            this.buyMain = buyMain == null ? new BuyMain(): buyMain; 
            this.setVisible(false);
        });
    }
}
