package Login;
import DATA.Database;
import MAIN.MainScreen;
import MAIN.NewMain;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Screen extends javax.swing.JFrame {
    private MainScreen mainScreen;
    private Register register;
    public Screen() {
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        setupActions();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        use_name = new javax.swing.JLabel();
        txtuse_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ButtonLog = new javax.swing.JButton();
        Buttontest = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        use_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        use_name.setText("TÀI KHOẢN:");
        getContentPane().add(use_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));
        getContentPane().add(txtuse_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MẬT KHẨU:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 20));

        ButtonLog.setText("ĐĂNG NHẬP");
        ButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        Buttontest.setText("ĐĂNG KÝ");
        getContentPane().add(Buttontest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //khi ấn nút đăng nhập
    private void ButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogActionPerformed
        try {
            // ket noi database
            Connection conn  = Database.getConnection();
            String user_name = txtuse_name.getText();
            String password  = txtpassword.getText();
            //tao doi tuong Statement
            Statement stmt = conn.createStatement();
            //cau lenh sqlkiểm tra xem tài khoản mật khẩu đúng hay chưa
            String sql = "SELECT * FROM user_id WHERE user_name='"+user_name+"' and password='"+password+"'";
            PreparedStatement pst = conn.prepareCall(sql);//
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                MainScreen mainScreen= new MainScreen();
                mainScreen.show();
                this.hide();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "TÀI KHOẢN HOẶC MẬT KHẨU KHÔNG ĐÚNG");
                txtuse_name.setText("");
                txtpassword.setText("");
            }
            // ngat ket noi
            Database.closeConnection(conn);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonLogActionPerformed

   
    public static void main(String args[]) {
       new Screen().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLog;
    private javax.swing.JButton Buttontest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuse_name;
    private javax.swing.JLabel use_name;
    // End of variables declaration//GEN-END:variables
    private void setupActions() {

       Buttontest.addActionListener((ActionEvent actionEvent) -> {
            this.register = register == null ? new Register() : register;
            this.setVisible(false);
            }); 
    }
}
